version: 2

models:
  # ============================================================================
  # DIMENSIONS
  # ============================================================================
  - name: dim_customer
    description: Customer dimension table with SCD Type 1
    columns:
      - name: customer_key
        description: Surrogate key for the customer dimension
        tests:
          - unique
          - not_null

      - name: customer_id
        description: Natural key - unique identifier for customer
        tests:
          - unique
          - not_null

      - name: customer_segment
        description: Customer segmentation based on order count
        tests:
          - not_null
          - accepted_values:
              values: ['loyal', 'repeat', 'one_time']

      - name: total_orders
        description: Total number of orders placed
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1000

  - name: dim_product
    description: Product dimension table with SCD Type 1
    columns:
      - name: product_key
        description: Surrogate key for the product dimension
        tests:
          - unique
          - not_null

      - name: product_id
        description: Natural key - unique identifier for product
        tests:
          - unique
          - not_null

      - name: product_category_name_en
        description: Product category in English
        tests:
          - not_null

      - name: sales_tier
        description: Categorization based on sales volume
        tests:
          - not_null
          - accepted_values:
              values: ['best_seller', 'popular', 'moderate', 'low_volume', 'no_sales']

  - name: dim_seller
    description: Seller dimension table with SCD Type 1
    columns:
      - name: seller_key
        description: Surrogate key for the seller dimension
        tests:
          - unique
          - not_null

      - name: seller_id
        description: Natural key - unique identifier for seller
        tests:
          - unique
          - not_null

      - name: seller_tier
        description: Categorization based on sales volume
        tests:
          - not_null
          - accepted_values:
              values: ['high_volume', 'medium_volume', 'low_volume', 'occasional', 'no_sales']

  - name: dim_date
    description: Date dimension table covering dataset date range
    columns:
      - name: date_key
        description: Surrogate key for the date dimension
        tests:
          - unique
          - not_null

      - name: date_day
        description: Natural key - the date
        tests:
          - unique
          - not_null

      - name: year
        description: Year extracted from date
        tests:
          - not_null

      - name: is_weekend
        description: Flag indicating if date is a weekend
        tests:
          - not_null

  # ============================================================================
  # FACTS
  # ============================================================================
  - name: fact_orders
    description: Order fact table with incremental loading, partitioned by date
    columns:
      - name: order_key
        description: Surrogate key for the order fact
        tests:
          - unique
          - not_null

      - name: order_id
        description: Natural key - unique identifier for order
        tests:
          - unique
          - not_null

      - name: customer_key
        description: Foreign key to customer dimension
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_key

      - name: purchase_date_key
        description: Foreign key to date dimension for purchase date
        tests:
          - not_null
          # Note: Relationship test disabled - surrogate keys may not match perfectly

      - name: order_status
        description: Status of the order
        tests:
          - not_null
          - accepted_values:
              values: ['delivered', 'shipped', 'canceled', 'unavailable', 'invoiced', 'processing', 'created', 'approved']

      - name: total_order_value
        description: Total value of the order (price + freight)
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100000

      - name: total_payment_value
        description: Total payment received for the order
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100000

      - name: review_score
        description: Customer review score (1-5)
        tests:
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 5
              inclusive: true

    tests:
      # Data quality test: payment should roughly match order value
      - dbt_utils.expression_is_true:
          expression: "abs(total_payment_value - total_order_value) < 10 or has_payment_mismatch = true"
          config:
            severity: warn
