version: 2

models:
  - name: mart_sales_daily
    description: >
      Daily sales metrics aggregated by date, product category, and customer state.
      Pre-aggregated for optimal dashboard performance.

    config:
      tags: ['mart', 'sales']

    columns:
      - name: order_date
        description: Date of the order
        tests:
          - not_null

      - name: product_category
        description: Product category in English

      - name: customer_state
        description: Customer state (BR state code)

      - name: total_orders
        description: Total number of orders
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"

      - name: total_revenue
        description: Total revenue in BRL
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"

      - name: delivery_rate_pct
        description: Percentage of orders delivered
        tests:
          - dbt_utils.expression_is_true:
              expression: "between 0 and 100 or delivery_rate_pct is null"

      - name: on_time_rate_pct
        description: Percentage of on-time deliveries
        tests:
          - dbt_utils.expression_is_true:
              expression: "between 0 and 100"

  - name: mart_sales_monthly
    description: >
      Monthly sales metrics with month-over-month and year-over-year growth calculations.
      Optimized for executive dashboards and trend analysis.

    config:
      tags: ['mart', 'sales']

    columns:
      - name: month_date
        description: First day of the month
        tests:
          - not_null

      - name: product_category
        description: Product category in English

      - name: customer_state
        description: Customer state (BR state code)

      - name: total_orders
        description: Total orders in the month
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"

      - name: total_revenue
        description: Total revenue in the month (BRL)
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"

      - name: mom_revenue_growth_pct
        description: Month-over-month revenue growth percentage

      - name: yoy_revenue_growth_pct
        description: Year-over-year revenue growth percentage

      - name: avg_daily_orders
        description: Average daily orders in the month
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"

      - name: avg_daily_revenue
        description: Average daily revenue in the month
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"

  - name: mart_customer_cohorts
    description: >
      Customer cohort analysis based on acquisition month.
      Includes lifetime value, segment distribution, and cohort performance metrics.

    config:
      tags: ['mart', 'customer']

    columns:
      - name: cohort_month
        description: Month when customers made their first purchase
        tests:
          - not_null

      - name: customer_state
        description: Customer state (BR state code)

      - name: cohort_size
        description: Number of customers acquired in this cohort
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"

      - name: customer_ltv
        description: Customer lifetime value (average revenue per customer)
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"

      - name: avg_orders_per_customer
        description: Average number of orders per customer in cohort
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"

      - name: loyal_pct
        description: Percentage of loyal customers (3+ orders)
        tests:
          - dbt_utils.expression_is_true:
              expression: "between 0 and 100"

      - name: repeat_pct
        description: Percentage of repeat customers (2 orders)
        tests:
          - dbt_utils.expression_is_true:
              expression: "between 0 and 100"

      - name: one_time_pct
        description: Percentage of one-time customers
        tests:
          - dbt_utils.expression_is_true:
              expression: "between 0 and 100"

  - name: mart_customer_retention
    description: >
      Month-by-month retention analysis showing cohort retention rates over time.
      Enables retention curve analysis and churn prediction.

    config:
      tags: ['mart', 'customer']

    columns:
      - name: cohort_month
        description: Month when customers made their first purchase
        tests:
          - not_null

      - name: activity_month
        description: Month of customer activity
        tests:
          - not_null

      - name: customer_state
        description: Customer state (BR state code)

      - name: months_since_cohort
        description: Number of months since cohort month (0 = acquisition month)
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"

      - name: cohort_size
        description: Original size of the cohort
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"

      - name: active_customers
        description: Number of customers active in this month
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"

      - name: retention_rate_pct
        description: Retention rate (active customers / cohort size)
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "between 0 and 100"

      - name: mom_retention_pct
        description: Month-over-month retention percentage
        tests:
          - dbt_utils.expression_is_true:
              expression: "between 0 and 100 or mom_retention_pct is null"

      - name: cumulative_revenue
        description: Cumulative revenue from cohort through this month
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"

  - name: mart_product_performance
    description: >
      Product performance metrics by month including rankings, growth rates,
      and category comparisons. Optimized for product analytics and inventory planning.

    config:
      tags: ['mart', 'product']

    columns:
      - name: month_date
        description: First day of the month
        tests:
          - not_null

      - name: product_id
        description: Unique product identifier
        tests:
          - not_null

      - name: product_category
        description: Product category in English

      - name: sales_tier
        description: Product sales tier (best_seller, high_volume, etc.)

      - name: total_orders
        description: Total orders for this product in the month
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"

      - name: total_revenue
        description: Total revenue for this product in the month (BRL)
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"

      - name: avg_review_score
        description: Average review score for the product
        tests:
          - dbt_utils.expression_is_true:
              expression: "between 1 and 5 or avg_review_score is null"

      - name: category_revenue_rank
        description: Revenue rank within category (1 = highest)
        tests:
          - dbt_utils.expression_is_true:
              expression: "> 0"

      - name: overall_revenue_rank
        description: Overall revenue rank (1 = highest revenue product)
        tests:
          - dbt_utils.expression_is_true:
              expression: "> 0"

      - name: mom_revenue_growth_pct
        description: Month-over-month revenue growth percentage

      - name: on_time_delivery_pct
        description: Percentage of on-time deliveries
        tests:
          - dbt_utils.expression_is_true:
              expression: "between 0 and 100 or on_time_delivery_pct is null"

      - name: freight_pct
        description: Freight cost as percentage of total revenue
        tests:
          - dbt_utils.expression_is_true:
              expression: "between 0 and 100"

  # ============================================================================
  # NEW EXECUTIVE ANALYTICS MODELS
  # ============================================================================

  - name: mart_customer_retention_quarterly
    description: >
      Quarterly customer retention analysis tracking repeat purchase rates.
      Core metric for retention strategy and executive reporting.

    config:
      tags: ['mart', 'customer', 'retention', 'executive']

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - cohort_quarter_start
            - customer_state
            - customer_city
            - quarters_since_cohort

    columns:
      - name: cohort_quarter_start
        description: First day of acquisition quarter
        tests:
          - not_null

      - name: customer_state
        description: Customer state
        tests:
          - not_null

      - name: customer_city
        description: Customer city
        tests:
          - not_null

      - name: quarters_since_cohort
        description: Quarters since acquisition (0 = acquisition quarter)
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 20

      - name: retention_rate_pct
        description: Quarterly repeat purchase rate
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
              inclusive: true

      - name: ltv_to_date
        description: Customer lifetime value to date
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100000

  - name: mart_geographic_performance
    description: >
      State and city-level performance analysis for geographic expansion strategy.
      Identifies market opportunities and concentration risks.

    config:
      tags: ['mart', 'geographic', 'executive']

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - customer_state
            - customer_city

    columns:
      - name: customer_state
        description: Customer state
        tests:
          - not_null

      - name: customer_city
        description: Customer city
        tests:
          - not_null

      - name: total_revenue
        description: Total revenue from this geography
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

      - name: retention_rate_pct
        description: Customer retention rate
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
              inclusive: true

      - name: expansion_priority
        description: Strategic expansion priority
        tests:
          - not_null
          - accepted_values:
              values:
                - 'Expand Aggressively'
                - 'Expand Cautiously'
                - 'Fix Operations First'
                - 'Monitor'

      - name: market_maturity
        description: Market maturity classification
        tests:
          - not_null
          - accepted_values:
              values:
                - 'High Potential'
                - 'Established'
                - 'Premium Niche'
                - 'Developing'
                - 'Mature'

  - name: mart_unit_economics
    description: >
      CAC payback and unit economics analysis by cohort.
      **NOTE:** Currently uses estimated CAC. Replace with actual marketing spend data.

    config:
      tags: ['mart', 'economics', 'executive']

    columns:
      - name: cac
        description: Customer acquisition cost (currently estimated)
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1000

      - name: ltv_cac_ratio
        description: Lifetime value to CAC ratio (healthy > 3.0)
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100

      - name: cohort_health_score
        description: Cohort health score (0-100)
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
              inclusive: true

      - name: unit_economics_status
        description: Unit economics assessment
        tests:
          - not_null
          - accepted_values:
              values:
                - 'CRITICAL: Not recovering CAC'
                - 'WARNING: Low margins'
                - 'ACCEPTABLE: Room for improvement'
                - 'GOOD: Healthy unit economics'
                - 'EXCELLENT: Strong unit economics'

  - name: mart_churn_prediction
    description: >
      Rule-based churn prediction model identifying at-risk customers.
      Uses RFM + behavioral signals for retention prioritization.

    config:
      tags: ['mart', 'churn', 'executive', 'ml']

    columns:
      - name: customer_key
        description: Unique customer identifier
        tests:
          - unique
          - not_null

      - name: churn_risk_score
        description: Composite churn risk score (0-100)
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
              inclusive: true

      - name: churn_probability
        description: Churn probability (0-1)
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1
              inclusive: true

      - name: churn_status
        description: Current churn status
        tests:
          - not_null
          - accepted_values:
              values:
                - 'Churned'
                - 'At Risk'
                - 'Declining'
                - 'Active'

      - name: churn_risk_segment
        description: Risk segmentation for prioritization
        tests:
          - not_null
          - accepted_values:
              values:
                - 'Critical Risk'
                - 'High Risk'
                - 'Medium Risk'
                - 'Low Risk'
                - 'Healthy'

      - name: retention_priority
        description: Retention campaign priority
        tests:
          - not_null

  - name: mart_category_performance
    description: >
      Product category performance analysis for diversification strategy.
      Identifies growth opportunities and risk concentrations.

    config:
      tags: ['mart', 'category', 'executive']

    columns:
      - name: category
        description: Product category (English)
        tests:
          - unique
          - not_null

      - name: total_revenue
        description: Total category revenue
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

      - name: revenue_share_pct
        description: Category share of total revenue
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
              inclusive: true

      - name: strategic_tier
        description: Strategic importance tier
        tests:
          - not_null
          - accepted_values:
              values:
                - 'Core Category'
                - 'Growth Category'
                - 'Emerging Category'
                - 'Niche Category'

      - name: performance_status
        description: Performance assessment
        tests:
          - not_null
          - accepted_values:
              values:
                - 'Star Performer'
                - 'Solid Performer'
                - 'Needs Improvement'
                - 'Under Development'
                - 'Stable'

  - name: mart_executive_summary
    description: >
      Executive KPI summary consolidating all critical metrics.
      Single source of truth for C-suite dashboard.

    config:
      tags: ['mart', 'executive', 'kpi']

    columns:
      - name: quarter_start
        description: First day of quarter
        tests:
          - unique
          - not_null

      - name: total_revenue
        description: Quarterly total revenue
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

      - name: revenue_growth_qoq_pct
        description: Quarter-over-quarter revenue growth

      - name: quarterly_retention_rate_pct
        description: Q1 repeat purchase rate
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
              where: "quarterly_retention_rate_pct is not null"

      - name: strategic_health_score
        description: Overall business health score (0-100)
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
              inclusive: true
